sigiem/config/routes.rb
Sigiem::Application.routes.draw do

  root to: 'main_pages#home'
  match '/acerca', to: 'main_pages#about'

  match '/registrate', to: 'users#new'
  resources :users, except: [:show] do
    member do
      post 'change_role'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/entrar', to: 'sessions#new'
  match '/salir', to: 'sessions#destroy', via: :delete
    
  resources :categories, except: [:show] do
    member do
      post 'data'
    end
  end

  resources :data, only: [:new, :create, :index, :destroy]

  resources :devices, only: [:edit, :update, :destroy, :index]
  match '/sensors_data', to: "devices#sensors_data", via: :post
  
  match '/emulator', to: "emulators#new"
  resources :emulators, only: [:create]
  
  resources :record_alerts, only: [:index, :destroy]
  match '/info_alerts', to: "record_alerts#info", via: :get
  match '/destroy_record', to: "record_alerts#destroy_record", via: :delete

  resources :wms_servers, except: [:show]
  

end

sigiem/app/models/category.rb
class Category
  include MongoMapper::Document
  safe

  attr_accessible :name, :parent

  key :name, String, required: true, length: 0..30
  key :parent, String, required: false, length: 0..30, default: "", :case_sensitive => false

  validates_uniqueness_of :name, :case_sensitive => false

  before_save :downcase_properties
  after_save :add_new_parent_as_category
  after_update :add_new_parent_as_category

  one :datum

  
  private

  def downcase_properties
    self.name.downcase!
    self.parent.downcase!
  end
  
  def add_new_parent_as_category
    if not Category.distinct(:name).include? self.parent
      Category.create(name: self.parent, parent: "")
    end
  end
  
end

sigiem/app/controllers/categories_controller.rb
#coding: utf-8
class CategoriesController < ApplicationController

  before_filter :signed_in, except: [:data]
  before_filter :signed_in_as_admin, except: [:data]

  def index
    @categories=Category.sort(:name).paginate(page: params[:page], per_page: 10)
  end

  def new
    @category=Category.new
  end

  def create
    @category=Category.new(params[:category])

    if @category.save
      flash[:success]="Categoría creada correctamente."
      redirect_to categories_path
    else
      render 'new'
    end
    
  end

  def edit
    @category=Category.find_by_id(params[:id])
  end

  def update
    
    @category=Category.find_by_id(params[:id])

    if @category.update_attributes(params[:category])
      flash[:success]="Categoría actualizada correctamente."
      redirect_to categories_path
    else
      flash[:error]="No se ha podido actualizar los datos."
      render "edit"
    end
    
  end

  def destroy
    category=Category.find(params[:id])
    if category.destroy

      if category.datum
        category.datum.destroy
      end
      
      flash[:success]= "La categoría y todos sus datos asociados han sido borrados correctamente."
    else
      flash[:error]= "No se ha podido borrar la categoría."
    end
    
    redirect_to categories_path
  end

  
  def data

    category=Category.find_by_id(params[:id])
    if not category.nil?
      data=Datum.find_by_category_id(category.id)
    end
    
    respond_to do |format|
      format.js do
        #empty categories (without data) and invalid categories
        if data.nil? 
          render :status => :no_content
        else
          @result= {
            geojson: JSON.generate(data.geojson).html_safe,
            id: category.id.to_s
          }
        end
      end
    end
    
  end

  
end

sigiem/app/helpers/categories_helper.rb
module CategoriesHelper
  
  def data_source_for_categories
    list=Category.distinct(:name).to_s
  end

  def options_for_categories_text_field(place_holder="Mostrar...", options={})
    default_options={
      :'data-provide'=> "typeahead",
      :'data-source'=> data_source_for_categories,
      placeholder: place_holder,
      :'data-items'=>"6"
    }

    return default_options.merge(options)
  end
  
end

sigiem/app/views/categories/_category_form.html.erb
<%= form_for(@category) do |f| %>

  <%= render 'shared/errors', form_object: @category %>

  <%= f.label :name,"Nombre" %>
  <%= f.text_field :name %>

  <%= f.label :parent, "Categoría a la que pertenece" %>
    <%= f.text_field :parent, 'data-provide'=> "typeahead", 'data-source'=> data_source_for_categories %>

  <%= f.submit button_text, class: "btn btn-large btn-primary" %>
			  

<%= link_to "Cancelar",categories_path, class: "btn btn-large btn-inverse" %>

<% end %>

sigiem/app/views/categories/data.js.erb
L.Icon.Default.imagePath="/assets";
<% if not @result.nil? %>
  var id_geojson="<%= @result[:id] %>";
  var geojson=<%= @result[:geojson] %>;

  layer_cache[id_geojson]=L.geoJson(geojson,
				  {
				      style: add_style,
				      onEachFeature: add_popup_info
				  }
				 );

layer_cache[id_geojson].addTo(map);
<% end %>

sigiem/app/views/categories/edit.html.erb
<% provide(:title, "Editar categoría") %>

<div class="row">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Modifica la categoría</h1>
    </div>

    <%= render 'category_form', button_text: "Actualizar datos" %>

  </div>
</div>

sigiem/app/views/categories/index.html.erb
<% provide(:title, "Categorías") %>

<div class="row">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Listado de categorías</h1>
    </div>

    <h3>
      <%= link_to "Añadir categoría", new_category_path, class: "btn btn-primary" %> </h3>

<div class="paginate">
  <%= will_paginate %>
</div>

<% if @categories.empty? %>
  <p><h4>Todavía no hay ninguna categoría.</h4></p>
<%end%>

<% @categories.each do |category| %>
<div class="categories">
  
  <h4> <%= category.name.capitalize%> 
    <small><%= "("+category.parent.capitalize+")" unless category.parent.blank? %> </small>
  </h4>

  <div class="categories_buttons">
    <% warning_message= "¿Estás seguro que deseas eliminar esta categoría" %>
    <% warning_message+= " y todos sus datos asociados (#{category.datum.name})" if category.datum %>
    <% warning_message+= "?" %>
      
    <%= link_to "Modificar datos", edit_category_path(category), class: "btn btn-info" %>
    <%= link_to "Eliminar categoría", category_path(category), method: :delete, class: "btn btn-danger", confirm: warning_message %>
  </div>

</div>
<% end %>

<div class="paginate">
  <%= will_paginate %>
</div>

  </div>
</div>

sigiem/app/views/categories/new.html.erb
<% provide(:title, "Añadir categoría") %>

<div class="row">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Añade una categoría</h1>
    </div>

    <%= render 'category_form', button_text: "Añadir categoría" %>

  </div>
</div>