sigiem/config/routes.rb
Sigiem::Application.routes.draw do

  root to: 'main_pages#home'
  match '/acerca', to: 'main_pages#about'

  match '/registrate', to: 'users#new'
  resources :users, except: [:show] do
    member do
      post 'change_role'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/entrar', to: 'sessions#new'
  match '/salir', to: 'sessions#destroy', via: :delete
    
  resources :categories, except: [:show] do
    member do
      post 'data'
    end
  end

  resources :data, only: [:new, :create, :index, :destroy]

  resources :devices, only: [:edit, :update, :destroy, :index]
  match '/sensors_data', to: "devices#sensors_data", via: :post
  
  match '/emulator', to: "emulators#new"
  resources :emulators, only: [:create]
  
  resources :record_alerts, only: [:index, :destroy]
  match '/info_alerts', to: "record_alerts#info", via: :get
  match '/destroy_record', to: "record_alerts#destroy_record", via: :delete

  resources :wms_servers, except: [:show]
  

end

sigiem/app/models/device.rb
#coding: utf-8
class Device
  include MongoMapper::Document
  safe

  attr_accessible :name, :lat, :long, :sensors
  
  key :name, String, required: true, unique: true, :case_sensitive => false
  key :lat, Float, required: true
  key :long, Float, required: true

  many :sensors, :dependent => :destroy

  validates_presence_of :sensors
  before_save :downcase_properties
  validate :format_coordinates
  

  private

  def downcase_properties
    self.name.downcase!
  end
  
  def format_coordinates
    valid_lat=[-90, 90]
    valid_long=[-180, 180]

    if self.lat.nil? or self.long.nil?
      return
    end
    
    if not is_between?(self.lat,valid_lat) or not is_between?(self.long, valid_long)
      errors.add(:format_coordinates, "rango inválido de latitud: (-90º a 90º) o longitud (-180º a 180º)")
    end
    
  end

  def is_between? number, array_values

    if number >= array_values[0] and number <= array_values[1]
      return true
    end
    
    return false
  end
  
end

sigiem/app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  before_filter :signed_in, except: [:sensors_data]
  before_filter :signed_in_as_admin, except: [:sensors_data]

  
  def edit
    @device=Device.find_by_id(params[:id])
  end

  def update
    updated_correct=true
    @device=Device.find_by_id(params[:id])
    
    @device.sensors.each_index do |i|
      params_alert=params[:device][:sensors][i][:alert]
      sensor=@device.sensors[i]
      alert=sensor.alert
      
      if alert.nil?
        alert=Alert.new(params_alert)
        alert.sensor=sensor
        sensor.alert=alert
        updated_correct=alert.save
      else
        updated_correct=alert.update_attributes(params_alert)
      end

      if not updated_correct
        break
      end
    end #each sensor

    if updated_correct
      redirect_to devices_path
    else
      render "edit"
    end
    
  end
  

  def destroy
    @device=Device.find_by_id(params[:id])
    
    if @device.destroy
      flash[:success]="El dispositivo #{@device.name} se ha borrado completamente"
    else
      flash[:error]="Error al borrar el dispositivo."
    end
    redirect_to devices_path
  end

  def index
    @devices=Device.all
        
    respond_to do |f|
      f.js
      f.html
    end
  end

  
  def sensors_data
    
    if params[:sensor_values].nil?
      params[:sensor_values]=[]
    end

    params[:device_name].downcase!
    params[:sensor_name].downcase!
    params[:sensor_values].collect! { |string| string.to_i}

    @device=Device.find_by_name(params[:device_name])
    alert=Alert.new( limit_sup: params[:alert_limit_sup], limit_inf: params[:alert_limit_inf])
    
    #don't exists the device
    if @device.nil?

      @device=Device.new(name: params[:device_name], lat: params[:device_lat], long: params[:device_long])
      sensor=Sensor.new(name: params[:sensor_name], type: params[:sensor_type], values: params[:sensor_values], device: @device)
      sensor.alert=alert
      alert.sensor=sensor
      @device.sensors << sensor
      
    else

      @device.lat=params[:device_lat]
      @device.long=params[:device_long]

      sensor=@device.sensors.find_by_name(params[:sensor_name])
      #exists the device but don't exists that sensor
      if sensor.nil?

        sensor=Sensor.new(name: params[:sensor_name], type: params[:sensor_type], values: params[:sensor_values], device: @device)
        alert.sensor=sensor
        sensor.alert=alert
        @device.sensors << sensor
      else
        #exists the device and the sensor
        sensor.values << params[:sensor_values]

        if sensor.alert.nil?
          sensor.alert=alert
        else
          alert=sensor.alert
        end

        sensor.save
      end

    end

    alert.sensor=sensor
    @device.save
    if not alert.nil?
      alert.check_values_of_sensor
      alert.save
    end
    
    respond_to do |format|
      format.js
    end

  end
  
end

sigiem/app/views/devices/_alert_form.html.erb
<div class="alert_form">
  Alerta
  <%= form_parent.fields_for 'alert', alert do |f| %>

    <p>
      <%= f.label :limit_sup, "Límite superior" %>
      <%= f.number_field :limit_sup %>
    </p>

  <p>
    <%= f.label :limit_inf, "Límite inferior" %>
    <%= f.number_field :limit_inf %>
  </p>

  <% end %>
</div>

sigiem/app/views/devices/_device.html.erb
<div class="row-fluid">
  <div class="devices">
    <strong>
      <%= device.name.capitalize %>
    </strong>
    tiene  
    <strong>
      <%= device.sensors.length %>
    </strong>
    sensores 
    <br />

    <div class="devices_buttons">    
      <%= link_to "Eliminar datos", device_path(device), method: :delete, confirm: "¿Estás seguro de que deseas eliminar todos los datos registrados del dispositivo: #{device.name}?", class: "btn btn-danger"%> 

      <%= link_to "Configurar alertas", edit_device_path(device), class: "btn btn-primary"%>
    </div>
  </div>
</div>

sigiem/app/views/devices/_device_form.html.erb
<%= form_for(@device) do |f| %>

  <%= render 'shared/errors', form_object: @device %>
  
  <p>
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :lat, "Latitud" %>
    <%= f.number_field :lat, min: -90, max: 90 %>
  </p>

  <p>
    <%= f.label :long, "Longitud" %>
    <%= f.number_field :long, min: -180, max: 180%>
  </p>

  <div class="sensors">
    <%= render 'sensor_form', sensors: @device.sensors, form_parent: f %>
  </div>

   <%= f.submit text_button, class: "btn btn-large btn-primary" %>

<%= link_to "Cancelar",devices_path, class: "btn btn-large btn-inverse" %>

<% end %>

sigiem/app/views/devices/_sensor_form.html.erb
<% sensors.each do |sensor| %>

  <div class="sensor">
    Sensor
    <%= form_parent.fields_for "sensors", sensor, index: nil do |f| %>
      
      <p>
	<%= f.label :name, "Nombre" %>
	<%= f.text_field :name %>
      </p>

    <p>
      <%= f.label :type, "Tipo" %>
      <%= f.text_field :type %>
    </p>

    <div class="alerts">
      <%= render 'alert_form', alert: sensor.alert, form_parent: f %>
    </div>

  <% end %>
  </div>
  
<% end %>

sigiem/app/views/devices/edit.html.erb
<% provide(:title, "Configurar alertas") %>

<div class="row-fluid">
  <div class="span4 offset4">
    <div class="h1_forms">
      <h1>Configura las alertas</h1>
    </div>

    <%= render 'device_form', text_button: "Actualizar alertas" %>

  </div>
</div>

sigiem/app/views/devices/index.html.erb
<% provide(:title, "Dispositivos") %>

<div class="row-fluid">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Dispositivos</h1>
    </div>
    
    <% if @devices.empty? %>
    <p>
      <h3>
      No hay dispositivos que hayan enviado información.
      </h3>
    </p>
    <% else %>
       <%= render @devices %>
    <% end %>
    
  </div>
</div>

sigiem/app/views/devices/index.js.erb
L.Icon.Default.imagePath="/assets";
var layer_sensors=new L.LayerGroup();
var marker_sensor=null;

<% @devices.each do |device| %>

  marker_sensor=L.marker([<%= device.lat %>,<%= device.long %>]);
  var info="Dispositivo: "+"<b><%= device.name.capitalize %></b>"+"</br>"
  
  <% device.sensors.each do |sensor| %>
    info+="<b>"+ "<%= sensor.name.to_s %>"+"</b>: "
    <% last_value=sensor.values.last.to_s %>
    <% if last_value %>
      info+="<%= sensor.values.last.to_s%>"
    <% end %>
    info+="</br>"
  <% end %>

  marker_sensor.bindPopup(info);
  layer_sensors.addLayer(marker_sensor)

<% end %>
//cache
layer_cache["sensors"]=layer_sensors;
layer_cache["sensors"].addTo(map);

sigiem/app/views/devices/new.html.erb
<% provide(:title, "Añadir dispositivo") %>

<div class="row-fluid">
  <div class="span4 offset4">
    <div class="h1_forms">
      <h1>Añade un dispositivo</h1>
    </div>

    <%= render 'device_form', text_button: "Crear dispositivo" %>

  </div>
</div>