sigiem/config/routes.rb
Sigiem::Application.routes.draw do

  root to: 'main_pages#home'
  match '/acerca', to: 'main_pages#about'

  match '/registrate', to: 'users#new'
  resources :users, except: [:show] do
    member do
      post 'change_role'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/entrar', to: 'sessions#new'
  match '/salir', to: 'sessions#destroy', via: :delete
    
  resources :categories, except: [:show] do
    member do
      post 'data'
    end
  end

  resources :data, only: [:new, :create, :index, :destroy]

  resources :devices, only: [:edit, :update, :destroy, :index]
  match '/sensors_data', to: "devices#sensors_data", via: :post
  
  match '/emulator', to: "emulators#new"
  resources :emulators, only: [:create]
  
  resources :record_alerts, only: [:index, :destroy]
  match '/info_alerts', to: "record_alerts#info", via: :get
  match '/destroy_record', to: "record_alerts#destroy_record", via: :delete

  resources :wms_servers, except: [:show]
  

end

sigiem/app/views/layouts/_footer.html.erb
<div class="row-fluid">
  <div class="span12">
    
    <footer class="footer">

      <small>
	<%= link_to "SIGIEM", "https://bitbucket.org/dpzaba/sigiem" %>  realizado con: 
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %>,
	<%= link_to "Bootstrap", "http://twitter.github.com/bootstrap" %>,
	<%= link_to "MongoDB", "http://www.mongodb.org" %>,
	<%= link_to "CloudMade", "http://leaflet.cloudmade.com"%>.
      </small>

      <nav>
	<ul>
	  <li><%= link_to "Acerca de",   acerca_path %></li>
	</ul>
      </nav>

    </footer>

  </div>
</div>

sigiem/app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <%= link_to "SIGIEM",root_path, class:"brand", id: "sigiem" %>
      
      <!-- user menu -->
      <div class="btn-group pull-right">
	<% if signed_in? %>
	<% button_path="#" %>
	<% button_label="Menú de "+ current_user.name+"." %>
	<% data_toggle="dropdown"%>
	<% else %>
	<% button_path=entrar_path %>
	<% button_label="Iniciar sesión" %>
	<% data_toggle="#"%>
	<% end %>

	<a class="dropdown-toggle btn" data-toggle=<%= data_toggle %>
	href=<%= button_path %> >
	<i class="icon-user"></i> 
	<%= button_label%>

	<% if signed_in? %>
	<span class="caret"></span>
	<% end %>
      </a>
      
      <% if signed_in? %>
      <ul class="dropdown-menu">
	<li>
	  <%= link_to "Modificar mis datos", edit_user_path(current_user) %>
	</li>

	<% if admin? %>
	<li class="divider">
	</li>
	<li>
	  <%= link_to "Gestionar usuarios", users_path %>
	</li>
	<li>
	  <%# link_to "Gestionar servidores WMS", wms_servers_path %>
	</li>
	<li>
	  <%= link_to "Gestionar categorías", categories_path %>
	</li>
	<li>
	  <%= link_to "Gestionar datos", data_path %>
	</li>
	<li class="divider">
	</li>
	<li>
	  <%= link_to "Configurar Alertas", devices_path %>
	</li>
	<li>
	  <%= link_to "Registro de alertas", record_alerts_path %>
	</li>
	<li>
	  <%= link_to "Emulador de sensores", emulator_path %>
	</li>
	<% end %>

	<li class="divider">
	</li>

	<li>
	  <%= link_to "Salir", salir_path, method: "delete", confirm: "¿Estás seguro de que deseas cerrar la sesión?" %>
	</li>
      </ul>
      <% end %>
      
    </div> <!-- user menu -->

    <!-- navigation bar collapse -->
    <div class="nav-collapse">
      <ul class="nav">
	<li>
	  <%= link_to "Inicio", root_path %>
	</li>
	<li>
	  <%= link_to "Acerca de", acerca_path %>
	</li>
	<li>
	  <%= link_to "Regístrate", registrate_path  unless signed_in?%>
	</li>
      </ul>
    </div><!--/.nav-collapse -->
    
    <div class="logo_uclm">
      <%= image_tag "logo_uclm.png", alt: "UCLM" %>
    </div>

  </div>
</div>
</div>

sigiem/app/views/layouts/_ie.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--[if lte IE 8]>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.ie.css" />
    <![endif]-->

sigiem/app/views/layouts/_piwik.html.erb
<!-- Piwik --> 
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://www.dpzaba.com/piwik/" : "http://www.dpzaba.com/piwik/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 2);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://www.dpzaba.com/piwik/piwik.php?idsite=2" style="border:0" alt="" /></p></noscript>
<!-- End Piwik Tracking Code -->

sigiem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIGIEM : <%= yield(:title) %> </title>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
    <%= render 'layouts/ie' %> 

    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="SIGIEM: Sistema de Información Geográfica Integrado, Energético y Medioambiental. Por David Antonio Pérez Zaba.">
    <meta name="author" content="David Antonio Pérez Zaba">
    <meta name="keywords" content="David Antonio Pérez Zaba,David Pérez,dpzaba,SIGIEM,UCLM,GIS,SIG">

    <link rel="icon" type="image/png" href="/favicon.png">
      
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container-fluid">	    
      <% flash.each do |type, message| %>
	<div class="alert alert-<%= type %>">
	  <%= message %>
	</div>
      <% end %>
    </div>

    <% correct_container="container" %>
    <% if defined? @container %>
      <% correct_container=@container %>
    <% end%>
    
    <div class=<%= correct_container %> >	
      <%= yield %>
    </div>

    <div class="container-fluid">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= render 'layouts/piwik' if Rails.env.production? %> 

  </body>

</html>