sigiem/config/routes.rb
Sigiem::Application.routes.draw do

  root to: 'main_pages#home'
  match '/acerca', to: 'main_pages#about'

  match '/registrate', to: 'users#new'
  resources :users, except: [:show] do
    member do
      post 'change_role'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/entrar', to: 'sessions#new'
  match '/salir', to: 'sessions#destroy', via: :delete
    
  resources :categories, except: [:show] do
    member do
      post 'data'
    end
  end

  resources :data, only: [:new, :create, :index, :destroy]

  resources :devices, only: [:edit, :update, :destroy, :index]
  match '/sensors_data', to: "devices#sensors_data", via: :post
  
  match '/emulator', to: "emulators#new"
  resources :emulators, only: [:create]
  
  resources :record_alerts, only: [:index, :destroy]
  match '/info_alerts', to: "record_alerts#info", via: :get
  match '/destroy_record', to: "record_alerts#destroy_record", via: :delete

  resources :wms_servers, except: [:show]
  

end

sigiem/app/models/wms_server.rb
class WmsServer
  include MongoMapper::Document
  safe
  
  attr_accessible :name, :url

  key :name, String, required: true, length: 5..50, :case_sensitive => false
  key :url, String, required: true, unique: true, case_sensitive: true

  validates_length_of :url, minimum: 5
  #regex_url?
  #category?
  
end

sigiem/app/controllers/wms_servers_controller.rb
class WmsServersController < ApplicationController

  before_filter :signed_in
  before_filter :signed_in_as_admin
  
  def index
    @wms_servers=WmsServer.sort(:name).paginate(page: params[:page], per_page: 10)
  end

  def new
    @server=WmsServer.new
  end

  def create
    @server=WmsServer.new(params[:wms_server])
    if @server.save
      flash[:success]="Servidor creado correctamente."
      redirect_to wms_servers_path
    else
      render "new"
    end
  end

  def edit
    @server=WmsServer.find_by_id(params[:id])
  end

  def update
    @server=WmsServer.find_by_id(params[:id])
    
    if @server.update_attributes(params[:wms_server])
      flash[:success]= "Se han actualizado los datos correctamente."
      redirect_to wms_servers_path
    else
      render "edit"
    end
    
  end

  def destroy
    @server=WmsServer.find_by_id(params[:id])
    
    if @server.destroy
      flash[:success]= "Servidor borrado correctamente."
    else
      flash[:error]= "No se ha podido borrar ese servidor."
    end
    
    redirect_to wms_servers_path
  end
  
end

sigiem/app/helpers/wms_servers_helper.rb
module WmsServersHelper
end

sigiem/app/views/wms_servers/_server_form.html.erb
<%= form_for(@server) do |f| %>

  <%= render 'shared/errors', form_object: @server %>
  
  <%= f.label :name, "Nombre" %>
  <%= f.text_field :name %>

  <%= f.label :url, "URL" %>
  <%= f.text_field :url %>

  <%= f.submit button_text, class: "btn btn-large btn-primary" %>

<%= link_to "Cancelar",wms_servers_path, class: "btn btn-large btn-inverse" %>

<% end %>

sigiem/app/views/wms_servers/edit.html.erb
<% provide(:title, "Editar servidor WMS") %>

<div class="row">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Actualiza los datos del servidor</h1>
    </div>

    <%= render 'server_form', button_text: "Actualizar datos" %>

  </div>
</div>

sigiem/app/views/wms_servers/index.html.erb
<% provide(:title, "Servidores WMS") %>

<div class="row">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Listado de servidores WMS</h1>
      <h4> <small>(Hay un total de <%= @wms_servers.count %>)</small></h4>
    </div>

    <h3><%= link_to "Añadir servidor WMS", new_wms_server_path, class: "btn btn-primary" %></h3>

<div class="paginate">
  <%= will_paginate %>
</div>

<% if @wms_servers.empty? %>
<p>
  <h4>Todavía no hay ningún servidor WMS.</h4>
</p>
<%end%>

    <% @wms_servers.each do |server| %>
      <div class="serversWms">
	<h4> <%= server.name.capitalize %> </h4>
        <h5><small><%= server.url %></small></h5>
	
	<div class="server_buttons">
		<%= link_to "Modificar datos", edit_wms_server_path(server), class: "btn btn-info" %>
	<%= link_to "Eliminar servidor", wms_server_path(server), method: :delete, class: "btn btn-danger", data: { confirm: "¿Estás seguro que deseas eliminar este servidor?"} %>
	</div>
	
      </div>
      
    <% end%>

<div class="paginate">
  <%= will_paginate %>
</div>

  </div>
</div>

sigiem/app/views/wms_servers/new.html.erb
<% provide(:title, "Añadir WMS") %>

<div class="row">
  <div class="span6 offset3">
    <div class="h1_forms">
      <h1>Añade un servidor WMS</h1>
    </div>

    <%= render 'server_form', button_text: "Añadir servidor" %>

  </div>
</div>